/// <reference lib="WebWorker" />
/// <reference types="vite-plugin-pwa/client" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Tell TypeScript this is a Service Worker global scope
declare const self: ServiceWorkerGlobalScope;

/* ═══════════════════════════════════════════════════════════════════
   PRECACHE STATIC ASSETS
   vite-plugin-pwa injects the build manifest into self.__WB_MANIFEST
   This caches all JS, CSS, HTML, and assets generated by the build.
   ═══════════════════════════════════════════════════════════════════ */
precacheAndRoute(self.__WB_MANIFEST);

// Remove old caches whenever a new service worker activates
cleanupOutdatedCaches();

/* ═══════════════════════════════════════════════════════════════════
   API ROUTES — Stale-While-Revalidate
   Serve cached data instantly, then refresh from network in background.
   ═══════════════════════════════════════════════════════════════════ */

// Cache PG listings API (/api/pg/*)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/pg'),
  new StaleWhileRevalidate({
    cacheName: 'api-pg-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200], // Cache opaque and successful responses
      }),
      new ExpirationPlugin({
        maxEntries: 50,              // Keep max 50 PG listing responses
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Cache all other API calls with NetworkFirst (try network, fallback to cache)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

/* ═══════════════════════════════════════════════════════════════════
   STATIC RESOURCES — CacheFirst
   Images, fonts, and other static assets rarely change.
   ═══════════════════════════════════════════════════════════════════ */

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

/* ═══════════════════════════════════════════════════════════════════
   OFFLINE FALLBACK
   When navigation fails (no internet), show the offline page.
   ═══════════════════════════════════════════════════════════════════ */

const OFFLINE_PAGE = '/offline.html';

// Precache the offline fallback page so it's always available
// We add it manually since it's in /public and not part of the build manifest
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('offline-fallback').then((cache) => {
      return cache.add(OFFLINE_PAGE);
    })
  );
});

// Intercept navigation requests and serve offline fallback when needed
self.addEventListener('fetch', (event) => {
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(async () => {
        const cache = await caches.open('offline-fallback');
        const cachedResponse = await cache.match(OFFLINE_PAGE);
        return cachedResponse || new Response('Offline', { status: 503 });
      })
    );
  }
});

/* ═══════════════════════════════════════════════════════════════════
   SERVICE WORKER LIFECYCLE
   ═══════════════════════════════════════════════════════════════════ */

// Skip waiting so the new SW activates immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Claim clients so the SW controls all tabs immediately
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

